load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

go_library(
    name = "go_default_library",
    srcs = [
        "hmac.go",
    ],
    importpath = "cel.dev/cel-go/ext/security/hmac",
    deps = [
        "//cel:go_default_library",
        "//common/types:go_default_library",
        "//common/types/ref:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "hmac_test.go",
    ],
    embed = [
        ":go_default_library",
    ],
    deps = [
        "//cel:go_default_library",
        "//ext:go_default_library",
    ],
)
